# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partdb_app', '0002_customer_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmake',
            old_name='make',
            new_name='name',
        ),
    ]
